version: '3.1'

services:
  db:
    image: postgres:12.2
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: saas_project_app_dev
    ports:
      - "5432:5432"

volumes:
  db: